Added function to verify and get position of the user from their JWTtoken
VineethRV/timetablearchitect pull request #29
Opened 2024-11-16 05:35 UTC by VineethRV

Pass jwt token of user to the function getPosition in auth.ts to veirfy and get his position, organisation, roles etc

2024-11-16 09:09 UTC, VijeshVS requested changes

2024-11-16 09:09 UTC, VijeshVS commented on lib/actions/auth.ts
> +export type User={
Move this type to types file

2024-11-16 09:09 UTC, VijeshVS commented on lib/actions/auth.ts
> +    try{
Prisma does not throw any error if it is not able to find a record. It throws an error only if it is not able to reach db

2024-11-16 09:48 UTC, VineethRV commented on lib/actions/auth.ts
> +export type User={
ok

2024-11-17 01:54 UTC, VijeshVS approved these changes

2024-11-17 01:54 UTC, merged